### ISSUE TITLE
Phoronix forums broken

### ISSUE THREAD

**Issue by desbma** [r4vi/block-the-eu-cookie-shit-list#105]
This filter breaks the Phoronix forums: blank page instead of the usual page.

By dichotomy I narrowed it down to this filter (don't know which rule).

Example URL: https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/800597-gnome-3-16-on-fedora-22-wayland-vs-x-org/page2

**Comment by r4vi** [comment]
@desbma it seems to be ok for me but I'm logged out - is it a problem you're seeing while logged in?

**Comment by desbma** [comment]
I'm logged out too.

I'm using [uBlock](https://github.com/chrisaljoudi/uBlock) 0.9.3.5 and Firefox 37.

**Comment by desbma** [comment]
See https://github.com/chrisaljoudi/uBlock/issues/1382#issuecomment-102654099 for the explanation and possible fix.

**Comment by r4vi** [comment]
thanks I will add it, I've started using uMatrix at home (abp still at work) so I should be able to catch these things easier now

**Comment by desbma** [comment]
Thanks :smirk:
