### ISSUE TITLE
push rights?

### ISSUE THREAD

**Issue by S2-** [r4vi/block-the-eu-cookie-shit-list#111]
hello r4vi, would you mind giving me push rights to master? i would like to contribute to the repo more often, and push rights would make it easier.

**Comment by r4vi** [comment]
that's fine by me - I'd love the help. 

You should know that I run the `./genlist.sh` / `genlist.bat` file to ensure the checksum is correctly calculated after pusing. Can you confirm that it works for you on your PR? https://github.com/r4vi/block-the-eu-cookie-shit-list/pull/110

if everything is fine then I'll give you push rights. Thanks for helping with this

**Comment by S2-** [comment]
is this bb22a99 what you mean?

**Comment by r4vi** [comment]
yep perfect, if you could do that when pushing to master that'd be great - thanks

**Comment by S2-** [comment]
yup! awesome. can i merge my own pull request for a test?

**Comment by S2-** [comment]
oh you already did. never mind.

**Comment by r4vi** [comment]
oops I was too quick but feel free to just merge own PRs or just push to
master in future (I'm not precious about the history)
