### ISSUE TITLE
checksum mismatch in ABP for Firefox

### ISSUE THREAD

**Issue by lewisje** [r4vi/block-the-eu-cookie-shit-list#113]
I tried updating the subscription less than an hour ago and got that message, even though the very last commit was to update the checksum, about 11 hours ago.

**Comment by r4vi** [comment]
it might be this extra space: https://github.com/r4vi/block-the-eu-cookie-shit-list/commit/faa7df41d794e52603a014fd0fe046c26790bb1e#diff-04c57ebfc803be3b54f55a26a0cf6c8aR9

**Comment by r4vi** [comment]
just tried in firefox and no checksum error anymore
