### ISSUE TITLE
Rules ###cookies & ##.cookies are too unselective

### ISSUE THREAD

**Issue by 3c0** [r4vi/block-the-eu-cookie-shit-list#115]
The following rules are too loose and *may* break a lot of websites :
`###cookies`
`##.cookies`

Example, where cosmetic filtering is leading to a blank page on http://www.idealo.fr/ :
`<html class="FR no-gec desktop  js localstorage cookies" lang="fr-FR">`

**Comment by r4vi** [comment]
You might be right, I'll look at taking these out and seeing how things feel

**Comment by r4vi** [comment]
looks like these have been removed
