### ISSUE TITLE
Add new rules

### ISSUE THREAD

**Issue by lencc** [r4vi/block-the-eu-cookie-shit-list#116]
Please add new rules:
1) <code>##.cc-overlay.cc-cookies</code>
2) <code>##.cookie-note</code>
3) <code>###allow_cookies_container</code>
4) <code>###bcmsCookieInfoWrapper</code>
5) <code>###ckWarning</code>
6) <code>###cookie3arhMsg</code>
7) <code>###CookieBox</code>
8) <code>###cookiediv</code>
9) <code>###cookiesDisclaimer</code>
10) <code>###CookieSettings</code>
11) <code>###cookieTerms</code>
12) <code>###cookieWarn</code>
13) <code>###divCookies_pnlCookies</code>
14) <code>###icanhascookie</code>

They block cookie notifications, which appear on EU websites.

**Comment by lencc** [comment]
I found two more rules, please add them to your list as well:
15) <code>##.cookie-law.col-md-12</code>
16) <code>###ctl00_ctl00_cookieDiv</code>

**Comment by r4vi** [comment]
thanks @lencc I'll work on getting these added soon

**Comment by lencc** [comment]
I also discovered, there is a cookie notification appearing on www.translate.google.com (as well as on local Google Translate websites). I found 4 different rules so far (I hope they are not too broad):
<code>###gb > .gb_8.gb_da.gb_Jb</code>
<code>###gb > .gb_d.gb_Bb.gb_Ac</code>
<code>###gb > .gb_ia.gb_tb.gb_Jb</code>
<code>###gb > .gb_X.gb_wa.gb_Jb</code>

**Comment by r4vi** [comment]
The problem with google cookie notices is that these ids are minified css
classes, and every time they change their design the ids will be
regenerated :( I am searching for a way to block these properly (perhaps by
text content) :(

**Comment by lencc** [comment]
Okay. However, I've been using the international (english) Google Translate website as well as local version of Google Translate (i.e. in my native language) for quite some time and the upper four rules seem to be doing the job well. You could implement them and then see if they help.

**Comment by r4vi** [comment]
Ok I will do that, it'd be nice if we had some sort of way to check when
those things changed - maybe I'll set up some simple continuous integration
tests

**Comment by lencc** [comment]
Okay, great. Thanks!

**Comment by T3stX** [comment]
Can I use this thread to share my list?

###cookie_layer
###isCookieAccepted
###hw_cookie_law
###cadre_alert_cookies
###cookie-policies
###cookie-policy-info
###mrw_cookielaw_banner
###avviso_cookie
###norm_cookies
###banner_cookie
###CookielawBanner
##.alertcookie
###gld_cookie_flag
###popup-cookie
###footerCk
###cookie_policy_bar
###plugin_cookie_int
##.ce-banner
###cookies-overlay
###cookies_banner
###cookie-policy-div
###cookiefascia

**Comment by lencc** [comment]
@T3stX I added all your rules to pull request. I also added few of my rules as well.
I hope the list will be updated soon.

**Comment by r4vi** [comment]
closed by #120 and #119
