### ISSUE TITLE
pizza-online.fi

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#118]
https://pizza-online.fi/

pizza-online.fi###cookie_policy_container

**Comment by jawz101** [comment]
You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter

**Comment by r4vi** [comment]
@jawz101 I'm not sure what you mean here,  they're asking for cookie notices to be blocked

**Comment by jawz101** [comment]
I guess I misunderstood.  This user is also going around requesting things like Disqus be allowed.  I don't think the add-on should be tailored to one person's choosing if they can simply whitelist what they want.

https://github.com/EFForg/privacybadgerfirefox/issues

**Comment by anonsubmitter** [comment]
I've understood, but this is not the right place for this discussion to take place, unless you have any comments regarding a cookie notice on a Finnish pizza site
