### ISSUE TITLE
web.skype.com

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#122]
https://web.skype.com/en/ (you have to be logged in to see the cookie notice)

web.skype.com##.notification.info

**Comment by jawz101** [comment]
I understand what you're saying but what you suggest to fix is what you'd do if you want to use them. If they do not honor Do Not Track then that's what you'd have to do but it's a commenting system based on a tracking mechanism. The whole concept is to make a tracker into a feature... which isn't great. I just allow it temporarily if I am compelled to read or write comments but it's not as if I want it to follow me around everywhere Disqus is.

https://en.wikipedia.org/wiki/Disqus#Criticism_and_privacy_concerns

You're going around submitting a ton of these tickets essentially unblocking tracking cookies.
https://github.com/anonsubmitter
