### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#126]
https://www.facebook.com/

facebook.com###u_0_v

**Comment by lencc** [comment]
I see no cookie notifications on Facebook.
As far as I tested your rule, it only disables chat column on the right side. Therefore I believe your rule cannot be implemented in this list. The list doesn't block any content except for cookie notifications.

**Comment by r4vi** [comment]
thanks for testing @lencc

**Comment by anonsubmitter** [comment]
I see a cookie notice on Facebook: https://imgur.com/a/sLRaq

Other options are ```facebook.com##[role="alert"]``` and ```facebook.com##.pam.fbPageBanner._3d9x.uiBoxGray.bottomborder```.

**Comment by lencc** [comment]
I'm sorry, I forgot to check the login page (I was logged in automatically).
The rule <code>facebook.com##[role="alert"]</code> seems to be working fine. Thanks!

**Comment by r4vi** [comment]
I wonder if role alert is too broad as they might use it for other alerts

**Comment by anonsubmitter** [comment]
How about ```facebook.com##.pam.fbPageBanner._3d9x.uiBoxGray.bottomborder``` then?

**Comment by lencc** [comment]
This one works okay for me as well.
