### ISSUE TITLE
Galleria.io blocked by Block-The-EU-Cookie-Shit-List

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#130]
[Galleria.io](http://galleria.io/) is being blocked by Block-The-EU-Cookie-Shit-List.

Whitelist filter rule:
`galleria.io#@#.cookiebanner`

**Comment by r4vi** [comment]
@anonsubmitter thanks for all the recent additions; I will add them all this weekend
