### ISSUE TITLE
blocks tweakers.net

### ISSUE THREAD

**Issue by DavidStaron** [r4vi/block-the-eu-cookie-shit-list#139]
http://tweakers.net/

You can't access the site without accepting the cookies...

**Comment by r4vi** [comment]
looks ok to me, can you post exact url where it is broken so I can try with filter on and off

**Comment by DavidStaron** [comment]
The exact url is http://tweakers.net/ 
(delete all cookies/cache of "tweakers.net" first). Here's 2 screenshots of the page and the request log:

![screen shot 2015-09-27 at 18 44 50](https://cloud.githubusercontent.com/assets/1530401/10123978/531cf4d4-6548-11e5-8fd5-107dc44af0f6.png)

![screen shot 2015-09-27 at 18 45 06](https://cloud.githubusercontent.com/assets/1530401/10123980/59b6458e-6548-11e5-96a1-efac178e40ac.png)
