### ISSUE TITLE
telia.se, tv.nu, www.sf.se

### ISSUE THREAD

**Issue by jimmywarting** [r4vi/block-the-eu-cookie-shit-list#141]
www.telia.se##DIV[class="tsAttention--Info--button"]
www.tv.nu##DIV[class="js-cookie-notice"]
www.sf.se##DIV[id="CookiesAreBeingUsed"][class="cookieMessageWrapper"]

**Comment by r4vi** [comment]
most of these are already blocked  except `www.telia.se##.tsAttention--Info--button`
