### ISSUE TITLE
Privilege generic filters

### ISSUE THREAD

**Issue by T3stX** [r4vi/block-the-eu-cookie-shit-list#144]
When it's possible to have a filter that refer unequivocally at cookie banners, prefer generic filters instead of per-site filters so they could works in other site.

Some example from the current filterlist.txt:
```
...
accuweather.com###eu-cookie-notify-wrap
actu-environnement.com###informations-cookies
anglianwater.co.uk###ctl00_pnlCookie
asda.com###FT_Cookies
audion.com###cc-cookies
barbie.com###eu_cookies_overlay_content
barclaycard.co.uk###cookiesMessageBanner
bfmtv.com###conteneurCookies
bikebuster.dk##.cookiesBlock
...
```

Should be:
```
...
###eu-cookie-notify-wrap
###informations-cookies
###ctl00_pnlCookie
###FT_Cookies
###cc-cookies
###eu_cookies_overlay_content
###cookiesMessageBanner
###conteneurCookies
##.cookiesBlock
...
```

**Comment by desbma** [comment]
This would increase the risk of breaking sites.
See #105 or #115.

**Comment by T3stX** [comment]
The issues you report are referred at 2 sites and 2 particular (and extremely generic) filters.
In my opinion it's better to create less filters and add few exclusions instead of hundred custom per-site filters. It's true this method needs some debug to work correctly.

Also gorhill suggest an exception filter as solution.
