### ISSUE TITLE
blocking too much

### ISSUE THREAD

**Issue by salim-b** [r4vi/block-the-eu-cookie-shit-list#206]
The filterlist blocks entire sites (cosmetic filtering), examples include [digitec.ch](https://www.digitec.ch/) or [account.post.ch](https://account.post.ch). Please have a look.

**Comment by r4vi** [comment]
@salim-b thanks for reporting, I let a overly broad ##.cookies fitlter pass through - I've removed in e9068248af391adb2f6a67c7cb8bb22f21b3e26b
