### ISSUE TITLE
www.espn.co.uk

### ISSUE THREAD

**Issue by wmyrda** [r4vi/block-the-eu-cookie-shit-list#208]
Adblock2privoxy converter threats [this line](https://github.com/r4vi/block-the-eu-cookie-shit-list/blob/master/filterlist.txt#L1146) as an error. Seems that rule `www.espn.co.uk/##.cookie-overlay` should not have `/` between domain name and hashes.

**Comment by r4vi** [comment]
thanks I'll fix it on Sunday
