### ISSUE TITLE
List support repair sites?

### ISSUE THREAD

**Issue by krystian3w** [r4vi/block-the-eu-cookie-shit-list#215]
https://github.com/MajkiIT/polish-ads-filter/issues/15452

blank page by generic:

https://github.com/r4vi/block-the-eu-cookie-shit-list/blob/c20b209500c47dd8e1950d1e10bf5e9c8895667e/filterlist.txt#L581

`https://www.lazienkaplus.pl/pl/kompakty-wc,8,88,c/` 

![obraz](https://user-images.githubusercontent.com/35370833/71549175-4619b580-29b9-11ea-9e1d-f043625b6bbf.png) |
--- |

## Fix:

```
lazienkaplus.pl#@#.cookies-policy
```

or add into generic filter:

```
:not(body):not(html)
```

**Comment by krystian3w** [comment]
I don't do PR because I don't know how you fix, like adding exceptions?
Additionally, I can't generate a checksum for Adblock Plus (I guess the 3.X version doesn't use them anymore...).

**Comment by r4vi** [comment]
@krystian3w thanks, I'll put this in soon - haven't turned on the computer during christmas break but will look into it soon
