### ISSUE TITLE
k-market.fi

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#88]
http://www.k-market.fi/

(I'm not sure which "element code" is preferred to use for blocking this cookie notice.)

**Comment by r4vi** [comment]
I guess it would be something like: ##div[data-ng-controller="AcceptCookiesController"]

**Comment by anonsubmitter** [comment]
Or just ##[data-ng-controller="AcceptCookiesController"]

Here's what fanboy did with the cookie notice: https://forums.lanik.us/viewtopic.php?f=62&t=21821

Another option is ##[data-ng-hide="isCookieAccepted"]
