### ISSUE TITLE
Cookie notices on British sites

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#96]
##.cookieConsent (Should cover all websites made via hibu, like http://bradmoorevanhire.co.uk/ | More examples: https://www.google.co.uk/#q=%22Web+design+by+hibu%22)

monster.co.uk###intMsgCookies
rspb.org.uk###cookie-message
santander.co.uk##.bloqueMensaje

I can't find a good filter rule for Johnston Press newspaper websites, such as http://www.haylingtoday.co.uk/ and http://www.northamptonchron.co.uk/

**Comment by r4vi** [comment]
cookieConsent already blocked
monster already blocked
###cookie-message already blocked

**Comment by r4vi** [comment]
http://www.haylingtoday.co.uk/ and http://www.northamptonchron.co.uk/ both blocked already
