### ISSUE TITLE
Cookie notices on Dutch sites

### ISSUE THREAD

**Issue by anonsubmitter** [r4vi/block-the-eu-cookie-shit-list#97]
ad.nl###cookiestatement
bol.com###cookie_message_container
http://www.npo.nl/
http://www.powned.tv/
rocmondriaan.nl##.cookie-popup

**Comment by r4vi** [comment]
generic blocks:
###cookiestatement already blocked
###cookie_message_container already blocked
##.cookie-popup already blocked

powned and npo seem to already have filters not showing their cookienotice
